services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PROD_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - PROD_DATASOURCE_USERNAME=postgres
      - PROD_DATASOURCE_PASSWORD=postgres
      - PROD_HOST_PORT=8080
    depends_on:
      - db

  db:
    container_name: db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432'
